### ISSUE TITLE
Optuna 2.4 | Can't instantiate abstract class DaskStorage 

### ISSUE THREAD

**Issue by quantabox** [jrbourbeau/dask-optuna#22]
Steps to recreate 

`pip install dask_optuna`
`conda install python`

Select Package Versions 
```python:  3.9.1
dask_optuna: 0.0.2
optuna: 2.4.0 
scipy: 1.4.0
numpy: 1.19
```
 
Execute example script

```import optuna
import joblib
import dask.distributed
import dask_optuna

def objective(trial):
    x = trial.suggest_uniform("x", -10, 10)
    return (x - 2) ** 2

with dask.distributed.Client() as client:
    # Create a study using Dask-compatible storage
    storage = dask_optuna.DaskStorage()
    study = optuna.create_study(storage=storage)
    # Optimize in parallel on your Dask cluster
    with joblib.parallel_backend("dask"):
        study.optimize(objective, n_trials=100, n_jobs=-1)
    print(f"best_params = {study.best_params}")
```

error message:
```Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
TypeError: Can't instantiate abstract class DaskStorage with abstract methods get_study_directions, set_study_directions, set_trial_values
```
the example works fine with optuna: 2.3.0.

**Comment by jrbourbeau** [comment]
Thanks for reporting this issue @quantabox! There were some known changes in the Optuna 2.4 release which broke the `DaskStorage` class here. We're working to incorporate `DaskStorage` directly into Optuna over in https://github.com/optuna/optuna/pull/2023 which will address the changes in the Optuna 2.4 release. In the meantime, as you've pointed out, I'd recommend sticking with `optuna < 2.4.0` for now

**Comment by fonnesbeck** [comment]
This still occurs in 2.5.0

**Comment by LeoFeilke** [comment]
Any news on this issue? Cant use any RDB storage with Optuna 2.3.0, DaskStorage included.

**Comment by eracle** [comment]
Same error here, it seems to not work even with Optuna 2.3.0

**Comment by Silk760** [comment]
same issue here, any update

**Comment by deepakagrawal** [comment]
Same error here.

**Comment by pseudotensor** [comment]
same

**Comment by pseudotensor** [comment]
@jrbourbeau given the work in optuna is difficult to complete, I wonder if there is a patch you could recommend for this repo to work with Optuna 2.5+?

**Comment by gcaria** [comment]
Even when downgrading to `optuna==2.3.0` this still does not work:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_366/788111577.py in <module>
     12 
     13 # Create an Optuna study using a Dask-compatible Optuna storage class
---> 14 storage = dask_optuna.DaskStorage()
     15 
     16 study = optuna.create_study(

/srv/conda/envs/notebook/lib/python3.9/site-packages/dask_optuna/storage.py in __init__(self, storage, name, client)
    309     def __init__(self, storage=None, name: str = None, client: Client = None):
    310         self.name = name or f"dask-storage-{uuid.uuid4().hex}"
--> 311         self.client = client or get_client()
    312 
    313         if self.client.asynchronous or getattr(

/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/worker.py in get_client(address, timeout, resolve_address)
   4086         return Client(address, timeout=timeout)
   4087     else:
-> 4088         raise ValueError("No global client found and no address provided")
   4089 
   4090 

ValueError: No global client found and no address provided
```

**Comment by Sarrae1406** [comment]
Issue still persists with version optuna 2.10.0.

TypeError: Can't instantiate abstract class DaskStorage with abstract methods get_study_directions, set_study_directions, set_trial_values

**Comment by daddydrac** [comment]
Error still persists:
```
TypeError                                 Traceback (most recent call last)
Input In [26], in <cell line: 5>()
      3 client_cluster = Client(cluster)
      5 with client_cluster as client:
----> 6     storage = dask_optuna.DaskStorage()
      7     study = optuna.create_study(
      8         study_name="pytorch-mlflow-optuna", 
      9         direction="minimize",
     10         storage=storage,
     11         sampler=optuna.samplers.TPESampler(search_space)
     12     )
     13     with joblib.parallel_backend("dask"):

TypeError: Can't instantiate abstract class DaskStorage with abstract methods get_study_directions, set_study_directions, set_trial_values
```

**Comment by kurvaraviteja355** [comment]
####
        with Client() as client:
                # Create a study using Dask-compatible storage
                dask_storage = dask_optuna.DaskStorage('sqlite:///example.db')
                study = optuna.create_study(storage=dask_storage)
                with joblib.parallel_backend("dask"):
                    study.optimize(optimize_model.objective, n_trials=50, n_jobs=-1)
                print(f"best_params = {study.best_params}")
                print('Best params{} and best score{}'.format(study.best_params, study.best_value))
        
                best_params = study.best_params
###
Error still exist in 2.10.0 version


Traceback (most recent call last):
  File "c:/Users/raviteja.kurva/OneDrive - profiflitzer.de/Documents/Python_Scripts/Microsoft/Microsoft_Forecast/src/surface_model_train.py", line 391, in <module>
    dask_storage = dask_optuna.DaskStorage('sqlite:///example.db')
TypeError: Can't instantiate abstract class DaskStorage with abstract methods get_study_directions, set_study_directions, set_trial_values

**Comment by inzamamsafi** [comment]
Getting the same error with version 0.0.2.

Is there any fix?

**Comment by cherusk** [comment]
FWIW Still the case for optuna 3.0.5
